version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - jekyll_bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development

volumes:
  jekyll_bundle: 